### PR TITLE
Raise exceptions on failure in infoblox_api.rb so that converge will …

### LINKED ISSUE #1: Converge does not fail on error
I have only tested this with the infoblox_host_record resource thus far but from looking over the code I suspect the issue is valid for the other resources as well. If the operation fails (e.g. -- :create fails because of invalid parameters or a previously existing host record) an error message is shown in the log but the converge continues. IMO, the converge should fail when the action is unsuccessful.

This is with Chef 12.4.3

### PR DESCRIPTION
**Pull request by jcejohnson**
…be stopped.

Resolves #1

### CODE REVIEW

**Comment by adamleff** [comment]
@jcejohnson thanks for your PR!

While I agree with you in #1 that the error handling is not what a user should expect, I'm a bit conflicted in this approach in your PR. It's possible that other users are loading this cookbook in and using the library API and expecting the methods to return nil/false if it was unsuccessful. This would definitely be a breaking change for those users.

I think a safer approach would be to modify the recipes/providers in this cookbook to raise the exception rather than the helper library. This would allow other users of the helper library to continue as-is, but you still gain the behavior you're expecting.  For example, in recipes/reserve_ip_in_network.rb:

``` ruby
unless next_available_ip
  raise "reserve_ip_in_network: unable to reserve, no available IP found"
else
  # rest of recipe here
end
```

What are your thoughts?

**Comment by jcejohnson** [comment]
If infoblox_api.rb were purely a gem I would agree but since this is an LWRP and Infoblox::Api exists to support the LWRP resources I think I disagree. IMO, it is a misuse of a cookbook to pull it in simply to use a helper library in its internal implementation -- users should simply use the infoblox gem to do what they need for that use case. However, if you feel strongly about allowing direct use of Infoblox::Api, I can refactor the PR to raise exceptions in the providers which is arguably the best of both worlds :-)

**Comment by adamleff** [comment]
I don't necessarily advocate for a user to load in this cookbook and misuse the API as a gem, but it's possible it's happening. For example, a user could have a wrapper cookbook that depends on this cookbook, use recipes from this cookbook, but then have their own providers/recipes in their wrapper cookbook that rely on the libraries in this one. In the interest of DRY, I would probably end up doing just that if I wanted to reuse their already-created methods. :smile: 

I think it would be best to refactor to raise exceptions in the recipes and providers. I'm still going to major-bump this though, so if you feel very strongly that doing this in the API is the best course of action, convince me and we can move forward. :)

**Comment by jcejohnson** [comment]
I'll refactor to raise exceptions in the providers. I don't feel good about raising exceptions in recipes since anyone using the resources would have to do that.

As i look at the providers, I'm having trouble understanding the intent behind some of the actions. For instance, if I add this resource to my cookbook's recipe, what am I expecting? Or, rather, how can the remaining recipe use the A record information that was fetched?

```
infoblox_a_record 'Get IP A-record' do
  name node['fqdn']
  action :get_record
end
```

**Comment by adamleff** [comment]
In that case, I don't think you are actually getting the record but rather creating it, and the action is just poorly named.

In any event, I'm going to dial back my paranoia and merge your changes. :) If anyone runs into issues, we'll approach it appropriately at that time.

Thanks for your contribution and having the conversation about the changes. I'll cut a new release shortly.

**Comment by adamleff** [comment]
v2.0.0 of the cookbook has been pushed up to the supermarket. Thanks again for your contribution. :)

**Comment by jcejohnson** [comment]
If you want to hold off for a bit, I've got another change that adds functionality to infoblox_host_record.

**Comment by adamleff** [comment]
Please drop it into another PR and we'll be happy to take a look!

**Pull request merged**
